version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.21
    container_name: consul    
    ports:
      - "8500:8500" 
      - "8600:8600/udp"
    environment:
      - CONSUL_UI_REFRESH_INTERVAL=2
    command: agent -dev -client=0.0.0.0
    networks:
      - service_discovery      
  servicea:
      build: ./ServiceA
      container_name: servicea
      ports:
      - "5000:80"
      networks:
      - service_discovery
  serviceb:
      build: ./ServiceB
      environment:
      - SERVICE_NAME=serviceb
      ports:
      - "5001:80"
      networks:
      - service_discovery
  serviceb1:
      build: ./ServiceB
      environment:
      - SERVICE_NAME=serviceb
      ports:
      - "5002:80"
      networks:
      - service_discovery
networks:
  service_discovery: